language: python
sudo: required
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install .
script: nosetests
matrix:
  allow_failures:
   - python: "nightly"
   - python: "3.6"
   - python: "3.7"
   - python: "pypy3"
   